!!python/object/new:dynamic_reconfigure.encoding.Config
dictitems: {ad_high: 80.0, ad_low: 0.0, adc8on: true, continuous: false, gain: 1.0,
  inverted: false, left_limit: 1.5707963267948966, mo_time: 74, nbins: 201, range: 3.92,
  right_limit: 4.649557127312894, scanright: false, speed: 1500.0, step: 0.12566370614359174}
state: []
