!!python/object/new:dynamic_reconfigure.encoding.Config
dictitems: {ad_high: 80.0, ad_low: 0.0, adc8on: true, continuous: false, gain: 1.0,
  inverted: false, left_limit: 1.3823007675795091, mo_time: 250, nbins: 400, range: 3.92,
  right_limit: 5.026548245743669, scanright: false, speed: 1500.0, step: 0.12566370614359174}
state: []
